### ISSUE TITLE
Create icons for action button

### ISSUE THREAD

**Issue by designedbinary** [conorgil/2fa-notifier#1]
Need a supported and not supported icon

**Comment by conorgil** [comment]
@designedbinary I got the three icons you shared offline. We can also use SVGs so that they get scaled automatically depending on the device. Is that easier than using PNGs?

**Comment by conorgil** [comment]
Docs: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action#Choosing_icon_sizes
