### ISSUE TITLE
subdomains are not being recognised.

### ISSUE THREAD

**Issue by thinksabin** [conorgil/2fa-notifier#105]
hi,
thanks for the great tool.
I dug into this after watching Tanya's OWASP DevSlop  video. And i found out this application is kind of data driven. I'm guessing data is in this file. (https://github.com/conorgil/2fa-notifier/blob/master/src/typescript/utils/dataService.ts)

In a Tanya's video she got false negative result notification cause she uses https://my.wealthsimple.com/app/login?redirect=%252F
page which is the subdomain for login.
And although your data does include wealthsimple.com in the list. The application is not parsing subdomains and hence false negative.

replication steps:
1. browse: https://www.wealthsimple.com/en-ca/
Green tick in the 2fa-notifier icon
2. click 'login' button in https://www.wealthsimple.com/en-ca/
sites redirects to the subdomain and the no more green tick in the 2fa-notifier

Thanks for this great tool again. Will love to it grow.

**Comment by conorgil** [comment]
Thanks for filing this issue! Issue #90 discusses this same problem. I just need to find the time to update the code and release a fix.
