### ISSUE TITLE
Chrome for Linux eports extension as being corrupted

### ISSUE THREAD

**Issue by oughter** [conorgil/2fa-notifier#27]
I get this situation reliably by:

- Running Chrome with the extension installed and enabled
- Going to a site that supports 2FA like github.com
- Clicking on the green 2FA Notifier button in the browser toolbar
- The button disappears, and in chrome://extensions, it shows

![screenshot from 2018-05-02 21-06-34](https://user-images.githubusercontent.com/18747026/39556328-a97aab28-4e4d-11e8-8d78-a03ad1c8c975.png)

Choosing the repair option does seem to work, but the flow is repeatable after the repair.

Extension version 0.2.1
Chrome version 66.0.3359.139

**Comment by conorgil** [comment]
@oughter I cannot replicate this. Can you think of any other details that might be specific to your setup? Is this still happening for you with the latest release?

**Comment by oughter** [comment]
This still happens for me with v0.5.0 of the extension. I can't replicate it either on macOS though, and the Firefox extension works fine on my Linux distro.

**Comment by conorgil** [comment]
@oughter are you still getting this corruption issue with 2FAN running in Chrome on Linux? I released several new versions, so maybe it magically fixed itself?

If not, then I'll leave open :)

**Comment by oughter** [comment]
The problem doesn't happen for me with v0.7.2 :+1:
