### ISSUE TITLE
Release this thing publicly already

### ISSUE THREAD

**Issue by ravenac95** [conorgil/2fa-notifier#30]
That's all.

**Comment by conorgil** [comment]
@designedbinary gave some TLC to the website and entry on the Chrome Store. We'll start sharing the extension on social media next week once we address a few last things that came up in early user testing 👍

**Comment by conorgil** [comment]
Boom! Done!

* [HN thread](https://news.ycombinator.com/item?id=17086377#17089390)
* [Twitter thread](https://twitter.com/conorgil/status/996835889010630656)
* [LinkedIn post](https://www.linkedin.com/feed/update/urn:li:activity:6402605618447859712)
* We shared it on our personal social networks (Facebook, etc)
