### ISSUE TITLE
Update messaging of CTA button for sites that support 2FA

### ISSUE THREAD

**Issue by conorgil** [conorgil/2fa-notifier#44]
Fixing up the messaging so it is more clear that we bring the user to the documentation that explains how to enable 2FA and that we don't actually enable 2FA. Through user testing, we saw that people were confused what clicking the "Enable 2FA" button would do and asked "Will this enable 2FA if I click this button?".

Button should say something more along the lines of "How to enable 2FA" or "learn more"

**Comment by designedbinary** [comment]
made a PR to address this: https://github.com/conorgil/2fa-notifier/pull/47

**Comment by conorgil** [comment]
We should continue to get feedback from users about whether the wording is clear
