### ISSUE TITLE
Need links for Conor's site, my site, and 2FAN email on the menu pages

### ISSUE THREAD

**Issue by designedbinary** [conorgil/2fa-notifier#5]

**Comment by designedbinary** [comment]
Conor's link's to ATA

**Comment by designedbinary** [comment]
@conorgil , there's one part I did not finish, and that is the email address. I'm assuming we'll have to make one somewhere? Maybe through ATA? I'll leave this part to you to create and update on the feedback.html page.

**Comment by conorgil** [comment]
@designedbinary and I chatted offline and decided to just point to the GitHub repo for now.

* Pros:
   * Transparency
   * Everyone can see all of the issues that were submitted, hopefully reducing dupes
   * Easier for us to keep track of feedback and not lose any via email, etc
* Cons:
   * Not as accessible for non-technical users
