### ISSUE TITLE
Icon on Notification on Windows 10 needs some padding

### ISSUE THREAD

**Issue by designedbinary** [conorgil/2fa-notifier#54]
![image](https://user-images.githubusercontent.com/2887189/40033516-96ca8f52-57ad-11e8-9617-e09e15e354ba.png)

The image is way too close to the edge of the notification. Need to check if this can be modified programmatically, or if it is better to just rework image to include the padding.

**Comment by conorgil** [comment]
@designedbinary worth a quick google search, but I am pretty sure that we cannot change that programmatically.
