### ISSUE TITLE
Handle sites that have no doc URL

### ISSUE THREAD

**Issue by conorgil** [conorgil/2fa-notifier#58]
![screen shot 2018-05-15 at 12 05 08 am](https://user-images.githubusercontent.com/945571/40036160-b4772170-57d3-11e8-9752-d97f8b028fb1.png)

We are not handling the scenario where there is no `doc` field for a given site. The link has `href="#"`, but also `target="_blank"`, so it opens a new page and shows the same page as the popup menu. Clearly, this looks horribly broken.

How should we handle this scenario?

Ideas:
* Create a page on 2fanotifier.org and link to that
* Replace the button with some default text
* Display the `exception` text from the `twofactorauth.org` if it is present

**Comment by designedbinary** [comment]
Holy Shit! This completely slipped my mind. Definitely agree about addressing this before we do an announcement blitz. 

What about changing the button to look disabled, and putting a message that says we can't find any docs?

**Comment by designedbinary** [comment]
![image](https://user-images.githubusercontent.com/2887189/40089797-a6b984da-5862-11e8-8131-545f8b3fa025.png)

What about something like this? The domain name might get too long..... need a more flexible solution.

**Comment by conorgil** [comment]
Reopening because this works in Chrome, but is broken in FF.
