### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by domoritz** [conorgil/2fa-notifier#65]
I love the extension and read through the code. I noticed that you could probably go without jQuery to save resources.

http://youmightnotneedjquery.com/ is a great guide.

**Comment by conorgil** [comment]
@domoritz totally agree. We threw in jQuery because it was quick and required less thinking. There is a ton of cleanup that we plan to do and removing jQuery is certainly something to look at. Thanks for checking it out!

**Comment by conorgil** [comment]
A friend just shared [this article](https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5) with me and I am bumping up the priority of removing jQuery as a result.

Benefits:
- smaller extension package size
- less code to audit/review (no, I didn't audit/review jQuery source, but that is kinda the point...)
- many others I'm sure

**Comment by conorgil** [comment]
Looks like removing jQuery shaved 80kb off the extension package size. Huzzah!

**Comment by conorgil** [comment]
We ended up saving 67kb: reduced package size from 540kb to 473kb
