### ISSUE TITLE
Onboarding v1

### ISSUE THREAD

**Issue by designedbinary** [conorgil/2fa-notifier#72]
Need initial onboarding. 

Onboarding should minimally convey:
- How notifications work
- The action bar icons, how they change, what they mean
- Where to find additional information (menu button)

**Comment by conorgil** [comment]
@designedbinary I just thought of/noticed a few things that we likely want to tweak/fix:
1. The 2FA Notifier text in the top left of the page should be a link to the homepage. Thoughts?
2. The URL only works for `/onboarding.html` and not `/onboarding`. I dunno why, but worth looking into whatever Jekyll or GitHub pages nonsense is going on there.

**Comment by designedbinary** [comment]
@conorgil 

1) Yup, you are right. We should do that. 

2) What are we trying to accomplish with `/onboarding`? Or is there a limitation with the extensions that only allow for `/onboarding` and not `/onboarding.html`?

3) Ah crap... I forgot to circle back on the homepage as I made some changes. Will do that.

**Comment by designedbinary** [comment]
Closing as all 3 issues have been addressed.
