### ISSUE TITLE
Touch up designs for "already enabled" feature

### ISSUE THREAD

**Issue by designedbinary** [conorgil/2fa-notifier#89]
Currently, the "already enabled" feature is bland and doesn't seem to quite fit the design. Need to run it through a few basic evaluations to see where we might be able to make improvements. 

- Run a review on UX
- Apply a more engaging confirmation screen
- Start ideating on a review page where you can manage all of your "2FA enabled" sites

**Comment by designedbinary** [comment]
@conorgil , could use your thoughts on this: 

![image](https://user-images.githubusercontent.com/2887189/43691046-7d301ed2-98ca-11e8-99c5-1e4ac17c4200.png)

Left: Simple revision of what you made

Middle: Confirmation screen that appears RIGHT after you hit "already enabled 2fa"

Right: In the future, if you hit the drop down again, this shows up to remind you that you've already enabled 2FA for this site. 

I'm debating on a "checkmark" instead of a "thumbs up" as it looks a bit shitty (both literally and figuratively)

Thoughts?

**Comment by conorgil** [comment]
Nice!!

Left: looks good

Middle: I think there is a typo or missing word in the first sentence? I like the second sentence. Love the image. Way better than the wall of text that I show now.

Right: Looks great. Maybe we can put the date that they clicked the "already enabled 2FA" link as a nice flourish. Also, maybe allow them to click a link "Remind me again on this site" or something in case they clicked the link by accident and didn't actually enable 2FA? Only a nice to have, not critical.

General:
I agree about the "thumbs up". Check mark might work better.
