### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by conorgil** [conorgil/2fa-notifier#93]
It was reported offline by @designedbinary  and in #87 that multiple notifications are popping up when a user visits a site that supports 2FA. 

What does happen: multiple notifications when you visit a site one time
What should happen: single notification per site
OS: Windows, Linux
Browsers: Chrome, FF

**Comment by conorgil** [comment]
@designedbinary and @JSkier21, you both reported this duplicate notification issue, so I wanted to ping you and let you know that it should be fixed. Let me know if you are still seeing dupes after updating to v0.7.2 and I will reopen this issue. Thanks for reporting this initially!

**Comment by JSkier21** [comment]
@conorgil, thank you, seems to work now in Linux (had to clear the cache in Firefox, initially it didn't seem to take). Tried about 10 sites and it popped up only once until I whitelisted it. 

Hate to turn this into a game of whack-a-mole for you, seeing an issue in Windows now. I don't seem get any notification balloons at all with Firefox 62 and 0.7.2 (will try to test another machine later, only seeing on one Win 7 box). However, Windows and Chrome seems fine (displays once in the lower right corner).

**Comment by conorgil** [comment]
@JSkier21 never apologize for providing valuable feedback! Hugely appreciated.

Great to hear FF on Linux is working. 

To make sure I follow the Windows situation:
- Windows 7, Firefox 62, 2FAN 0.7.2 = does not work
- Windows 7, Chrome, 2FAN 0.7.2 = does work

It would be great if you could test on another Windows machine if you have one. The following worked as expected for me: Windows 10, Firefox 62, 2FAN 0.7.2

**Comment by JSkier21** [comment]
Yes, that is correct. 

Will try Win 10 tonight.

**Comment by JSkier21** [comment]
Can't seem to replicate on Windows 10 (works fine) + Firefox 62. I'll look into this some more next week, but probably makes sense to keep this closed for now. Thank you again.

**Comment by conorgil** [comment]
@JSkier21 Thanks for the follow up! I will reopen this issue if anyone else reports similar issues with Win7 and FF.
